Bootstrap: shub
From: singularityhub/ubuntu

%runscript
    exec echo "The runscript is the containers default runtime command!"

%environment
    VARIABLE=MEATBALLVALUE
    export VARIABLE

%labels
   AUTHOR siturria@fing.edu.uy

%post
    apt-get update && apt-get -y install python3 git wget
    mkdir /data
    touch /siturria_was_here.txt
    echo "The post section is where you can install, and configure your container."
